SET unique_checks = 0;
SET foreign_key_checks = 0;
REPLACE INTO `uapa_db`.`v_colciencias_tipo_evento` ( `cod_tipo_evento`,`tipo_evento_col`,`tipo_evento_uapa`,`TIPO_UAPA`,`tipo_pregrado`,`tipo_posgrado`) VALUES (1,'Otro','Otro',null,null);
REPLACE INTO `uapa_db`.`v_colciencias_tipo_evento` ( `cod_tipo_evento`,`tipo_evento_col`,`tipo_evento_uapa`,`TIPO_UAPA`,`tipo_pregrado`,`tipo_posgrado`) VALUES (2,'Taller','Taller',null,null);
REPLACE INTO `uapa_db`.`v_colciencias_tipo_evento` ( `cod_tipo_evento`,`tipo_evento_col`,`tipo_evento_uapa`,`TIPO_UAPA`,`tipo_pregrado`,`tipo_posgrado`) VALUES (3,'Congreso','Congreso',null,null);
REPLACE INTO `uapa_db`.`v_colciencias_tipo_evento` ( `cod_tipo_evento`,`tipo_evento_col`,`tipo_evento_uapa`,`TIPO_UAPA`,`tipo_pregrado`,`tipo_posgrado`) VALUES (4,'Encuentro','Encuentro',null,null);
REPLACE INTO `uapa_db`.`v_colciencias_tipo_evento` ( `cod_tipo_evento`,`tipo_evento_col`,`tipo_evento_uapa`,`TIPO_UAPA`,`tipo_pregrado`,`tipo_posgrado`) VALUES (5,'Seminario','Seminario',null,null);
REPLACE INTO `uapa_db`.`v_colciencias_tipo_evento` ( `cod_tipo_evento`,`tipo_evento_col`,`tipo_evento_uapa`,`TIPO_UAPA`,`tipo_pregrado`,`tipo_posgrado`) VALUES (6,'Simposio','Simposio',null,null);
SET unique_checks = 1;
SET foreign_key_checks = 1;
